import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from './../lib/registry'
import * as ui from '@/lib/ui';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ui.Box>
            <ui.PageTitle>Home Page</ui.PageTitle>
          </ui.Box>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
